import { create } from "zustand";
export const useInvoiceStore = create((set) => ({
  orderNumber: "",
  setOrderNumber: (orderNumber) => set({ orderNumber }),
  customerName: "",
  setCustomerName: (customerName) => set({ customerName }),
  phoneNumber: "",
  setPhoneNumber: (phoneNumber) => set({ phoneNumber }),
  emailId: "",
  setEmailId: (emailId) => set({ emailId }),
  notes: "",
  setNotes: (notes) => set({ notes }),
  products: [],
  setProducts: (products) => set({ products }),
  subTotal: "₹0",
  setSubTotal: (subTotal) => set({ subTotal }),
  paid: "0",
  setPaid: (paid) => set({ paid }),
  tax: 18,
  setTax: (tax) => set({ tax }),
  taxValue: 0,
  setTaxValue: (taxValue) => set({ taxValue }),
  balance: "₹0",
  setBalance: (balance) => set({ balance }),
  isEditing: false,
  setIsEditing: (isEditing) => set({ isEditing }),
  showModal: false,
  setShowModal: (showModal) => set({ showModal }),
  paymentMode: "",
  setPaymentMode: (paymentMode) => set({ paymentMode }),
  coupon: "",
  setCoupon: (coupon) => set({ coupon }),
  couponDiscount: "",
  setCouponDiscount: (couponDiscount) => set({ couponDiscount }),
  store: {},
  setStore: (store) => set({ store }),
  invoiceDate: new Date().toLocaleDateString(),
  setInvoiceDate: (invoiceDate) => set({ invoiceDate }),
}));
